### ISSUE TITLE
npm run lint errors.

### ISSUE THREAD

**Issue by Aladdin-ADD** [caiogondim/fast-memoize.js#50]
![image](https://user-images.githubusercontent.com/13050025/28287269-95f9ef96-6b6d-11e7-9264-3794de144014.png)

**Comment by caiogondim** [comment]
Care to fix it?

**Comment by Aladdin-ADD** [comment]
some stylistic issues can be easily fixed. I will open a PR later.😄

**Comment by caiogondim** [comment]
I'm not getting those errors.
I'm trying to replicate with `npm run lint`

**Comment by Aladdin-ADD** [comment]
`npm run lint`

**Comment by caiogondim** [comment]
I get nothing...

**Comment by Aladdin-ADD** [comment]
so starnge! I reinstall the deps and try again, the errors as before.
eslint version: 3.19.0
eslint-config-standard: 6.2.1
eslint-plugin-standard: 2.3.1

what's yours?

**Comment by Aladdin-ADD** [comment]
Oh. got it. seems like eslint reade a config from my local.

![image](https://user-images.githubusercontent.com/13050025/28370948-24ef81be-6cce-11e7-8981-f768416a1183.png)

**Comment by Aladdin-ADD** [comment]
the question is I didn't find a config in the repo. Did you forget to commit?

**Comment by caiogondim** [comment]
Indeed, I forgot to add it.
I usually just use [standard.js](https://standardjs.com/)
You care to change it to standard.js?

**Comment by Aladdin-ADD** [comment]
I think it's better to have its config own -- others may not using standard in their local.

opened a PR to fix it. #55

**Comment by caiogondim** [comment]
standard doesn’t have a config file.
That’s why I like it and usually use it on my projects.

Sent from my iPhone

On July 19, 2017 at 10:36:39 AM, 薛定谔的猫 (notifications@github.com) wrote:

I think it's better to have its config own -- others may not using standard
in their local.

opened a PR to fix it. #55
<https://github.com/caiogondim/fast-memoize.js/pull/55>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/caiogondim/fast-memoize.js/issues/50#issuecomment-316407882>,
or mute the thread

**Comment by Aladdin-ADD** [comment]
but seems like you are using `eslint-config-standard`, not `standard`. so also need a config.
